modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://gitlab.com/sargunv-mc-mods/i-am-very-smart/issues"

[[mods]]
modId="iamverysmart"
version="${file.jarVersion}"
displayName="I Am Very Smart"
displayURL="https://minecraft.curseforge.com/projects/i-am-very-smart-forge"
authors="sargunv"
description="Unlock all recipes by default."

[[dependencies.iamverysmart]]
modId="minecraft"
mandatory=true
versionRange="[1.14.4]"
ordering="NONE"
side="BOTH"

[[dependencies.iamverysmart]]
modId="forge"
mandatory=true
versionRange="[28,)"
ordering="NONE"
side="BOTH"
