name: CI

on:
  push:
    branches: [mc-*]
  pull_request:
    branches: [mc-*]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch full history
      - uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: adopt
          cache: gradle
      - run: ./gradlew build
      - uses: actions/upload-artifact@v2.2.4
        with:
          path: build/libs/*.jar
          if-no-files-found: error
